/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hack;

import calculator_gui.NewJFrame;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;




public class options extends javax.swing.JFrame {
private final int red1=2;
private final int blu1=2;
private final int red2=2;
private final int blu2=2;
private final int red3=2;

private Timer timer;
int re1,bl1,re2,bl2,re3;
    /**
     * Creates new form options
     */
    public options() {
        
        initComponents();
        
        
       
      
     r1.setVisible(false);
     b1.setVisible(false);
     r2.setVisible(false);
     b2.setVisible(false);
     r3.setVisible(false);
        start();
    }
    private void start()
    {
        
       
        
                }
        
    


  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton22 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        r1 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        r2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        r3 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton53 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/navi2.jpeg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/navi2.jpeg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/hacker.jpeg"))); // NOI18N

        jButton15.setBackground(new java.awt.Color(204, 204, 204));
        jButton15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lock.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton36.setBackground(new java.awt.Color(255, 0, 51));
        jButton36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton36.setText("Disable Windows Update");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton22.setText("jButton22");

        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/black2.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/black2.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/hacker5.jpg"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/black2.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/hacker5.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(55, 5));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setSize(new java.awt.Dimension(50, 50));
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/anony.jpg"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(0);
        jButton7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(20, 90, 170, 150);

        jButton30.setBackground(new java.awt.Color(255, 255, 255));
        jButton30.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton30.setText("Repair My Internet");
        jButton30.setAlignmentY(1.0F);
        jButton30.setBorder(null);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(600, 360, 170, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/android.png"))); // NOI18N
        jButton5.setText("Repair My Phone");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(0);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(800, 420, 160, 130);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("Warning use them carefully !!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(980, 620, 150, 20);

        jButton17.setBackground(new java.awt.Color(50, 134, 134));
        jButton17.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/webblock.jpg"))); // NOI18N
        jButton17.setAlignmentX(5.0F);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(210, 420, 170, 130);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton12.setText("Command Based");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(400, 280, 170, 20);

        jButton21.setBackground(new java.awt.Color(0, 0, 0));
        jButton21.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Wifi Pass Revealer");
        jButton21.setBorder(null);
        jButton21.setOpaque(false);
        getContentPane().add(jButton21);
        jButton21.setBounds(400, 260, 170, 20);

        jButton23.setBackground(new java.awt.Color(0, 0, 0));
        jButton23.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 0, 0));
        jButton23.setText("Virus Remover");
        jButton23.setBorder(null);
        jButton23.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton23.setOpaque(false);
        jButton23.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(800, 180, 160, 50);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lock2.png"))); // NOI18N
        jButton13.setText("Sniffing");
        jButton13.setBorder(new javax.swing.border.MatteBorder(null));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(880, 650, 120, 30);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lock2.png"))); // NOI18N
        jButton14.setText("Facebook Password Bypass");
        jButton14.setBorder(new javax.swing.border.MatteBorder(null));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(80, 650, 200, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lock2.png"))); // NOI18N
        jButton10.setText("Website Crawling");
        jButton10.setBorder(new javax.swing.border.MatteBorder(null));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(650, 650, 220, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/back.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(0, -30, 30, 20);

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/back.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 0, 30, 20);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/malware.jpg"))); // NOI18N
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(800, 100, 160, 130);

        r1.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(r1);
        r1.setBounds(20, 600, 190, 9);

        jButton43.setBackground(new java.awt.Color(0, 0, 0));
        jButton43.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("Bypass Windows Password");
        jButton43.setBorder(null);
        jButton43.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton43.setOpaque(false);
        jButton43.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43);
        jButton43.setBounds(210, 210, 170, 20);

        jButton40.setBackground(new java.awt.Color(255, 255, 255));
        jButton40.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton40.setForeground(new java.awt.Color(0, 0, 102));
        jButton40.setText("MultiBoot");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton40);
        jButton40.setBounds(610, 500, 130, 30);

        b1.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(b1);
        b1.setBounds(250, 600, 180, 9);

        r2.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(r2);
        r2.setBounds(470, 600, 200, 9);

        b2.setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().add(b2);
        b2.setBounds(700, 600, 190, 9);

        jButton46.setBackground(new java.awt.Color(197, 19, 19));
        jButton46.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 255, 255));
        jButton46.setText("Delete Cache Windows Explorer");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton46);
        jButton46.setBounds(790, 50, 190, 30);

        jButton48.setBackground(new java.awt.Color(0, 204, 255));
        jButton48.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("Auto Shutdown/Sleep");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48);
        jButton48.setBounds(1010, 40, 150, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/internetrepair.jpg"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 260, 170, 120);

        jButton51.setBackground(new java.awt.Color(0, 0, 0));
        jButton51.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton51.setForeground(new java.awt.Color(0, 153, 255));
        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/255731.jpg"))); // NOI18N
        jButton51.setText("Mini Windows");
        jButton51.setBorderPainted(false);
        jButton51.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton51.setFocusPainted(false);
        jButton51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton51.setIconTextGap(0);
        jButton51.setMargin(new java.awt.Insets(-2, 10, 2, 14));
        jButton51.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton51.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton51.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton51.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51);
        jButton51.setBounds(600, 100, 170, 130);

        jButton52.setBackground(new java.awt.Color(255, 255, 255));
        jButton52.setFont(new java.awt.Font("Comic Sans MS", 1, 9)); // NOI18N
        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/acronis.png"))); // NOI18N
        jButton52.setText("Backup Windows");
        jButton52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton52.setIconTextGap(0);
        jButton52.setMargin(new java.awt.Insets(2, 14, 30, 14));
        jButton52.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton52);
        jButton52.setBounds(980, 260, 160, 130);

        jButton20.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/win10.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(400, 430, 160, 120);

        jButton54.setBackground(new java.awt.Color(153, 0, 255));
        jButton54.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 255, 255));
        jButton54.setText("Download Any Video Online");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton54);
        jButton54.setBounds(400, 50, 180, 30);

        jButton41.setBackground(new java.awt.Color(255, 255, 255));
        jButton41.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton41.setForeground(new java.awt.Color(102, 102, 255));
        jButton41.setText("UUI");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41);
        jButton41.setBounds(680, 450, 60, 40);

        jButton55.setBackground(new java.awt.Color(153, 0, 255));
        jButton55.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton55.setForeground(new java.awt.Color(255, 255, 255));
        jButton55.setText("Torrent Downloader");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton55);
        jButton55.setBounds(590, 50, 190, 30);

        jButton24.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/uac.png"))); // NOI18N
        jButton24.setBorder(null);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(800, 260, 160, 120);

        r3.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(r3);
        r3.setBounds(920, 600, 190, 9);

        jButton26.setBackground(new java.awt.Color(0, 0, 0));
        jButton26.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lock2.png"))); // NOI18N
        jButton26.setText("WPA/Wpa2 Psk Penetrate");
        jButton26.setBorder(new javax.swing.border.MatteBorder(null));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(420, 650, 220, 30);

        jButton28.setBackground(new java.awt.Color(0, 0, 0));
        jButton28.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lock2.png"))); // NOI18N
        jButton28.setText("Track Mobile");
        jButton28.setBorder(new javax.swing.border.MatteBorder(null));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(290, 650, 120, 30);

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bypass UAC");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(850, 380, 90, 10);

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 8)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Change Windows Password w/o Current Psw");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 410, 170, 20);

        jButton29.setBackground(new java.awt.Color(0, 0, 0));
        jButton29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("Search PC");
        jButton29.setBorder(null);
        jButton29.setOpaque(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(1010, 10, 70, 20);

        jButton31.setBackground(new java.awt.Color(0, 0, 0));
        jButton31.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("Who's on My Network ?");
        jButton31.setBorder(null);
        jButton31.setOpaque(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(20, 370, 160, 20);

        jButton32.setBackground(new java.awt.Color(0, 0, 0));
        jButton32.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/ipmac.png"))); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton32);
        jButton32.setBounds(20, 260, 160, 130);

        jButton39.setBackground(new java.awt.Color(255, 255, 255));
        jButton39.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton39.setForeground(new java.awt.Color(0, 153, 153));
        jButton39.setText("Rufus");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(610, 450, 70, 40);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/logowo.png"))); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setIconTextGap(0);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(210, 260, 170, 130);

        jButton33.setBackground(new java.awt.Color(0, 0, 0));
        jButton33.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("Partition Assistant");
        jButton33.setBorder(null);
        jButton33.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton33.setOpaque(false);
        jButton33.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(980, 530, 160, 20);

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/recover.jpg"))); // NOI18N
        jButton18.setText("Recover Deleted Files");
        jButton18.setAlignmentY(50.0F);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setIconTextGap(0);
        jButton18.setMargin(new java.awt.Insets(0, 10, 50, 14));
        jButton18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(20, 420, 160, 130);

        jButton25.setBackground(new java.awt.Color(0, 0, 0));
        jButton25.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/pdf.png"))); // NOI18N
        jButton25.setText("PDF Password Remover");
        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton25.setBorderPainted(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setIconTextGap(0);
        jButton25.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton25.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(980, 100, 160, 130);

        jButton27.setBackground(new java.awt.Color(0, 0, 0));
        jButton27.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/bootableusb.jpg"))); // NOI18N
        jButton27.setText("Make Pendrive Bootable");
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setIconTextGap(0);
        jButton27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(600, 420, 160, 130);

        jButton3.setBackground(new java.awt.Color(197, 19, 19));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Disable Windows Defender");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(790, 10, 190, 30);

        jButton4.setBackground(new java.awt.Color(197, 19, 19));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Disable Windows Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 10, 180, 30);

        jButton35.setBackground(new java.awt.Color(197, 19, 19));
        jButton35.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("Open CMD(admin)");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton35);
        jButton35.setBounds(520, 10, 130, 30);

        jButton37.setBackground(new java.awt.Color(197, 19, 19));
        jButton37.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("Disable Windows Firewall");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton37);
        jButton37.setBounds(340, 10, 170, 30);

        jButton38.setBackground(new java.awt.Color(255, 255, 255));
        jButton38.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/wifihack.gif"))); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38);
        jButton38.setBounds(400, 290, 170, 100);

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/maxresdefault.jpg"))); // NOI18N
        jButton19.setText("Bypass Windows Pwd");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setIconTextGap(0);
        jButton19.setMargin(new java.awt.Insets(20, 10, -20, 14));
        jButton19.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton19.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(210, 100, 170, 130);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/black.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-20, 390, 590, 400);

        jButton53.setBackground(new java.awt.Color(255, 153, 0));
        jButton53.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/AOMEI Partition Assistant Icon.png"))); // NOI18N
        jButton53.setText("Partition Assistant");
        jButton53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton53.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton53);
        jButton53.setBounds(980, 420, 160, 120);

        jButton34.setBackground(new java.awt.Color(197, 19, 19));
        jButton34.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("Disable UAC");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton34);
        jButton34.setBounds(670, 10, 100, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/redblue.gif"))); // NOI18N
        jButton11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton11MouseDragged(evt);
            }
        });
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton11MousePressed(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(1120, 570, 20, 20);

        jButton45.setBackground(new java.awt.Color(255, 0, 51));
        jButton45.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton45.setText("Disable Windows Defender");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton45);
        jButton45.setBounds(790, 50, 190, 30);

        jButton42.setBackground(new java.awt.Color(0, 0, 0));
        jButton42.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("Reveal Win Product Key");
        jButton42.setBorder(null);
        jButton42.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton42.setOpaque(false);
        jButton42.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jButton42);
        jButton42.setBounds(400, 100, 180, 20);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/productkey.jpg"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(0);
        jButton6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton6.setOpaque(false);
        jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(400, 110, 180, 120);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/black2.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, -10, 1400, 840);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/hacker5.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-20, -170, 790, 790);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
           
        helper ff = null;
        try {
            ff = new helper();
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
        ff.setVisible(true);             
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Magical Jelly Bean\\keyfind.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Done !! You are ready to surf in your browser anonymously. ","Have Patience :)",JOptionPane.INFORMATION_MESSAGE);
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Tor Browser\\Tor\\tore.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Subscribe Us :) To Get Full Access ","Only Rs.10/Month",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Subscribe Us :) To Get Full Access ","Only Rs.10/Month",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Subscribe Us :) To Get Full Access ","Only Rs.10/Month",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Subscribe Us :) To Get Full Access ","Only Rs.10/Month",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        
        bsite obj=new bsite();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Wondershare\\dr.fone toolkit for Android\\DrFoneAndroid.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        main1 obj68= new main1();
        obj68.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        main1 obj68= new main1();
        obj68.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Complete Internet Repair\\CompleteInternetRepair.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Avira\\AviraAntiVir\\aviracmd.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Subscribe Us :) To Get Full Access ","Only Rs.10/Month",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Subscribe Us :) To Get Full Access ","Only Rs.10/Month",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
    try {
        // TODO add your handling code here:
        helper1 obj8;
        obj8 = new helper1();
        obj8.setVisible(true);
    } catch (IOException ex) {
        Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
               try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Avira\\AviraAntiVir\\aviracmd.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\adip.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\adip.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Complete Internet Repair\\CompleteInternetRepair.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        uac uy =new uac();
        uy.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Windows & Office Activator\\MicrosoftToolkit.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Recuva\\Recuva.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        pcunlocker info1 = new pcunlocker();
        info1.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\PDF Password Remover\\Advanced PDF Password Recovery\\APDFPR.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Everything\\Everything.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Enable or Disable Defender\\DisableDefender.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\DisableWinUpdate\\DisableWinUpdate.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,"Please Reboot the Computer to apply the affect ","Reboot your computer !!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseDragged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton11MouseDragged

    private void jButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton11MousePressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         int speed=120;
            re1=red1;
            bl1=blu1;
            re2=red2;
            bl2=blu2;
            re3=red3;
            ActionListener action;
            action = new ActionListener(){
                public void actionPerformed(ActionEvent evt){
                    if(re1>=0)
                    {
                        r1.setVisible(true);
                        re1--;
                    }
                    else if(bl1>=0)
                    {
                        r1.setVisible(false);
                        b1.setVisible(true);
                        r2.setVisible(false);
                        b2.setVisible(false);
                        r3.setVisible(false);
                        bl1--;
                    }
                    else if(re2>=0)
                    {
                        r1.setVisible(false);
                        b1.setVisible(false);
                        r2.setVisible(true);
                        b2.setVisible(false);
                        r3.setVisible(false);
                        re2--;
                    }
                    else if(bl2>=0)
                    {
                        r1.setVisible(false);
                        b1.setVisible(false);
                        r2.setVisible(false);
                        b2.setVisible(true);
                        r3.setVisible(false);
                        bl2--;
                    }
                    else if(re3>=0)
                    {
                        r1.setVisible(false);
                        b1.setVisible(false);
                        r2.setVisible(false);
                        b2.setVisible(false);
                        r3.setVisible(true);
                        re3--;
                    }

                    else
                    {
                        r1.setVisible(false);
                        b1.setVisible(false);
                        r2.setVisible(false);
                        b2.setVisible(false);
                        r3.setVisible(false);

                        re1=red1;
                        bl1=blu1;
                        re2=red2;
                        bl2=blu2;
                        re3=red3;
                    }
                }
            };

            timer = new Timer(speed, action);
            timer.start();
            jButton11.setEnabled(false);
            jButton11.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
         
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Disable UAC\\Disable_uac.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Please Reboot the Computer to apply the affect ","Reboot your computer !!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\CommandPrompt\\cm.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JOptionPane.showMessageDialog(null,"Please Reboot the Computer to apply the affect ","Reboot your computer !!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null," ","Paste this in CMD ",JOptionPane.INFORMATION_MESSAGE);
        File file = new File("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Disable WinFirewall\\Disable Windows Firewall.txt");
         Desktop desktop = Desktop.getDesktop();
    try {
        desktop.open(file);
    } catch (IOException ex) {
        Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
    }
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\CommandPrompt\\cm.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Wifi Pass Revealer\\wifirevealer.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\MultiBoot USB\\xboot.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Rufus\\rufus.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Operation Completed Successfully !!  ","Done",JOptionPane.INFORMATION_MESSAGE);
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\ClearFileExplorerHistory\\Clear_File_Explorer_History.bat");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Wise Auto Shutdown\\WAS.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        CopyFiles info1 = new CopyFiles();
        info1.setVisible(true);
        
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // TODO add your handling code here:
        acronis in1 = new acronis();
        in1.setVisible(true);
        
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\AOMEI Partition Assistant Pro Edition 7.1\\aomei.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
        try {
   
   URI uri= new URI("https://catchvideo.net/");
   
   java.awt.Desktop.getDesktop().browse(uri);
    
 
  } catch (IOException | URISyntaxException e) {
  }
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\qBittorrent\\qbt.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\MakeUsbBootable\\UUI.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Process p = Runtime.getRuntime().exec("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\AOMEI Partition Assistant Pro Edition 7.1\\aomei.cmd");
        } catch (IOException ex) {
            Logger.getLogger(options.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
         pcunlocker info1 = new pcunlocker();
        info1.setVisible(true);
    }//GEN-LAST:event_jButton43ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton r1;
    private javax.swing.JButton r2;
    private javax.swing.JButton r3;
    // End of variables declaration//GEN-END:variables

    
}
