/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hack;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;



/**
 *
 * @author PC
 */
public class password_manager extends javax.swing.JFrame {
    
private final int red1=10;
private final int blu1=13;
private final int red2=10;
private final int blu2=10;
private final int red3=5;
private Timer timer;
int re1,bl1,re2,bl2,re3;
    /**
     * Creates new form options
     */
    public password_manager() 
    {
        
        
        initComponents();
        
        
        jTextField5.setVisible(false);
        jTextField3.setVisible(false);
        try(BufferedReader br = new BufferedReader(new FileReader("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\platforms\\account.txt"))) {
                 
    StringBuilder sb = new StringBuilder();
    String line = br.readLine();

    while (line != null) {
        sb.append(line);
        sb.append(System.lineSeparator());
        line = br.readLine();
    }
    String everything = sb.toString();
    String nospc = everything.replaceAll("\\s", "");
    jTextField2.setText(nospc);
      File f = new File("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\printsupport\\pswtxtencrypted_"+nospc+".txt");
     if(f.exists())
      {
       jButton2.setVisible(true);   
      }
     else
     {
             jButton2.setVisible(false);   
     }
     
    }   catch (IOException ex) {
            Logger.getLogger(password_manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
     j1.setVisible(false);
     j2.setVisible(false);
     j3.setVisible(false);
     j4.setVisible(false);
     j5.setVisible(false);
        start();
    }
    private void start()
    {
        
        int speed=200;
        re1=red1;
        bl1=blu1;
        re2=red2;
        bl2=blu2;
        re3=red3;
        ActionListener action;
    action = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
            if(re1>=0)
            {
                j1.setVisible(true);
                re1--;
            }
            else if(bl1>=0)
            {
                j1.setVisible(true);
                j2.setVisible(true);
                 j3.setVisible(false);
                j4.setVisible(false);
                 j5.setVisible(false);
                bl1--;
            }
            else if(re2>=0)
            {
                j1.setVisible(true);
                j2.setVisible(true);
                 j3.setVisible(true);
                j4.setVisible(false);
                 j5.setVisible(false);
                re2--;
            }
            else if(bl2>=0)
            {
                j1.setVisible(true);
                j2.setVisible(true);
                 j3.setVisible(true);
                j4.setVisible(true);
                 j5.setVisible(false);
                bl2--;
            }
            else if(re3>=0)
            {
                j1.setVisible(true);
                j2.setVisible(true);
                 j3.setVisible(true);
                j4.setVisible(true);
                 j5.setVisible(true);
                 jLabel2.setVisible(false);
                re3--;
            }
            
            
            else
            {
                j1.setVisible(true);
                j2.setVisible(true);
                j3.setVisible(true);
                j4.setVisible(true);
                j5.setVisible(true);
                jLabel2.setVisible(false);
                
                
               
            }
        }
    };
        
    timer = new Timer(speed, action);
                timer.start();
                }
    /**
     * Creates new form password_manager
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("typing...");
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/white.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/white.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/white.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/white.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 430));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Key");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 170, 50);

        j1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        j1.setForeground(new java.awt.Color(36, 193, 140));
        j1.setText("Hi , I am your password manager. ");
        getContentPane().add(j1);
        j1.setBounds(420, 220, 242, 30);

        j4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        j4.setForeground(new java.awt.Color(255, 0, 102));
        j4.setText("I am here to remember all those ");
        getContentPane().add(j4);
        j4.setBounds(420, 310, 450, 30);

        j2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        j2.setForeground(new java.awt.Color(130, 197, 31));
        j2.setText("From now onwards, there is no need ");
        getContentPane().add(j2);
        j2.setBounds(420, 250, 440, 30);

        j3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        j3.setForeground(new java.awt.Color(130, 197, 31));
        j3.setText("to remember password. ");
        getContentPane().add(j3);
        j3.setBounds(420, 280, 170, 30);

        j5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        j5.setForeground(new java.awt.Color(255, 0, 102));
        j5.setText("crucial passwords of your websites.");
        getContentPane().add(j5);
        j5.setBounds(420, 340, 270, 30);

        jLabel5.setBackground(new java.awt.Color(255, 204, 51));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("and let us manage with your data");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 130, 190, 20);

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(95, 181, 181));
        jLabel9.setText("Enter Details");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 100, 110, 26);

        jLabel10.setBackground(new java.awt.Color(255, 204, 51));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 270, 120, 40);

        jButton3.setBackground(new java.awt.Color(95, 181, 181));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Store");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 370, 75, 43);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Welcome ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 40, 100, 30);

        jTextField2.setBackground(new java.awt.Color(247, 247, 247));
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField2.setText(" ");
        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 40, 160, 30);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 2, 9)); // NOI18N
        jLabel12.setText("@ powered by WinAnalyst");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 40, 140, 40);

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 255));
        jLabel13.setText("Last");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(260, 0, 150, 50);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/loc.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 10, 60, 60);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("typing...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 200, 50, 20);

        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 200, 270, 200);

        jLabel14.setBackground(new java.awt.Color(255, 204, 51));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setText("Username");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 220, 119, 30);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 250, 190, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(90, 300, 190, 30);

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 51, 51));
        jTextField3.setBorder(null);
        jTextField3.setFocusable(false);
        jTextField3.setRequestFocusEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 330, 180, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Show Mine Stored Passwords");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 120, 240, 50);

        jLabel15.setBackground(new java.awt.Color(255, 204, 51));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel15.setText("Caption");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(90, 160, 119, 30);

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(90, 190, 190, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/white.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-1130, -500, 2010, 980);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(20, 380, 6, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        main1 info =new main1();
        info.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try(BufferedReader br = new BufferedReader(new FileReader("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\platforms\\account.txt"))) {
                 
    StringBuilder sb = new StringBuilder();
    String line = br.readLine();

    while (line != null) {
        sb.append(line);
        sb.append(System.lineSeparator());
        line = br.readLine();
    }
    String everything = sb.toString();
    String nospc = everything.replaceAll("\\s", "");
    jTextField2.setText(nospc);
      String cap= jTextField4.getText();
        String user= jTextField1.getText();
        String pa= jPasswordField1.getText();
                
        File log = new File("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\printsupport\\pswtxtencrypted_"+nospc+".txt");
    try{
    PrintWriter out = new PrintWriter(new FileWriter(log, true));
    out.append("******************\nDetails of "+cap+"\nUsername:"+user+"\nPassword:"+pa+"\n"+"\n*******************\n" + "\n");
    out.close();
    //JOptionPane.showMessageDialog(null,"Details Saved Successfully ","Saved",JOptionPane.ERROR_MESSAGE);
   
    this.dispose();
    
    
     saved ii2=new saved();
    ii2.setVisible(true);
   
    }catch(IOException e){
        System.out.println("COULD NOT LOG!!");
    }
    }   catch (IOException ex) {
            Logger.getLogger(password_manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try(BufferedReader br = new BufferedReader(new FileReader("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\platforms\\account.txt"))) {
                 
    StringBuilder sb = new StringBuilder();
    String line = br.readLine();

    while (line != null) {
        sb.append(line);
        sb.append(System.lineSeparator());
        line = br.readLine();
    }
    String everything = sb.toString();
    String nospc = everything.replaceAll("\\s", "");
    jTextField5.setText(nospc);     
        } catch (IOException ex) {  
        Logger.getLogger(password_manager.class.getName()).log(Level.SEVERE, null, ex);
    }

    String nospc11=jTextField5.getText(); 
       

   this.dispose();
   pswshow ob=new pswshow();
   ob.setVisible(true);

 
    
         
        
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password_manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new password_manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
