/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hack;

import static hack.hackframe.feq;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.DosFileAttributes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Navi Singh
 */
public class vaultv2 extends javax.swing.JFrame {

    /**
     * Creates new form vaultv2
     */
    public vaultv2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lockeee.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lockeee.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 380));
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Set Name for Your Vault :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 60, 240, 30);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 100, 280, 30);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GO");
        jButton1.setMinimumSize(new java.awt.Dimension(105, 105));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 200, 100, 50);

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/back.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 0, 30, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hack/lockeee.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-180, 0, 710, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String vaultfile = jTextField1.getText();
        
       
        
try(BufferedReader br = new BufferedReader(new FileReader("\\WinAnalyst CD 1.01.1\\config_files\\src\\fix\\qwerty\\Advanced IP Scanner\\platforms\\account.txt"))) {
    StringBuilder sb = new StringBuilder();
    String line = br.readLine();

    while (line != null) {
        sb.append(line);
        sb.append(System.lineSeparator());
        line = br.readLine();
    }
    String everything = sb.toString();
    String nospc1 = everything.replaceAll("\\s", "");
  
    File f = new File("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles");
    f.mkdir();

try{
            PrintStream myconsole;
            myconsole = new PrintStream(new File("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles\\locker.bat"));
            System.setOut(myconsole);
            myconsole.print("ren "+vaultfile+" Private.{645FF040-5081-101B-9F08-00AA002F954E}");
        } catch (FileNotFoundException fx) {
            System.out.println(fx);
        }
  try{
            PrintStream myconsole;
            myconsole = new PrintStream(new File("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles\\unlocker.bat"));
            System.setOut(myconsole);
            myconsole.print("ren Private.{645FF040-5081-101B-9F08-00AA002F954E} "+vaultfile);
        } catch (FileNotFoundException fx) {
            System.out.println(fx);
        }
Path p = Paths.get("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles\\unlocker.bat");

       //link file to DosFileAttributes
       DosFileAttributes dos = Files.readAttributes(p, DosFileAttributes.class);

       //hide the Log file
       Files.setAttribute(p, "dos:hidden", true);
  
  Path p2 = Paths.get("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles\\locker.bat");

       //link file to DosFileAttributes
       DosFileAttributes dos1 = Files.readAttributes(p2, DosFileAttributes.class);

       //hide the Log file
       Files.setAttribute(p2, "dos:hidden", true);
  
  
  
  File f1 = new File("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles\\"+vaultfile);
    f1.mkdir();
    feq = nospc1;
    
    Desktop d = null;
        File file = new File("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles");
            if(Desktop.isDesktopSupported());
            {
                d=Desktop.getDesktop();
            }
            try{
                d.open(file);
            }
            catch(java.io.IOException e){}

     try{
            PrintStream myconsole;
            myconsole = new PrintStream(new File("\\WinAnalyst CD 1.01.1\\Vault Files\\"+nospc1+"_vaultfiles\\vaultname.txt"));
            System.setOut(myconsole);
            myconsole.print(vaultfile);
        } catch (FileNotFoundException fx) {
            System.out.println(fx);
        }
         
}   catch (java.io.IOException ex) {
        Logger.getLogger(hackframe.class.getName()).log(Level.SEVERE, null, ex);
    }


this.dispose();
        vaultv22 ob11=new vaultv22();
        ob11.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        main1 obj68= new main1();
        obj68.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vaultv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vaultv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vaultv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vaultv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vaultv2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
